module.exports = {
    ratingLookup: {
        6: 'Rating Pending',
        39: 'Rating Pending',
        7: 'Everyone',
        8: 'Everyone',
        1: 'Everyone',
        13: 'Everyone',
        18: 'Everyone',
        24: 'Everyone',
        28: 'Everyone',
        24: 'Everyone',
        9: 'Everyone 10+',
        2: 'Everyone 10+',
        14: 'Everyone 10+',
        19: 'Everyone 10+',
        24: 'Everyone 10+',
        29: 'Everyone 10+',
        35: 'Everyone 10+',
        10: 'Teen',
        3: 'Teen',
        15: 'Teen',
        20: 'Teen',
        25: 'Teen',
        36: 'Teen',
        11: 'Mature',
        4: 'Mature',
        16: 'Mature',
        21: 'Mature',
        26: 'Mature',
        37: 'Mature',
        12: 'Adults Only',
        5: 'Adults Only',
        17: 'Adults Only',
        22: 'Adults Only',
        27: 'Adults Only',
        38: 'Adults Only'
    }
}